#!/usr/bin/env zsh

TEMPLATE=/tmp/vimdiff.XXXXXX
export TMPFILE=`mktemp $TEMPLATE`
export TMPDIR=`mktemp -d $TEMPLATE`
mkdir -p $TMPDIR/old $TMPDIR/new

if [[ -x /usr/local/bin/mvim ]]; then
    VIM_BINARY=mvim
elif [[ $SVLINUX = wsl ]]; then
    VIM_BINARY="${SV_GVIM_EXE:-gvim.exe}"
else
    VIM_BINARY=gvim
fi

cleanup() {
  rm -rf $TMPFILE $TMPDIR
}
trap "cleanup" SIGTERM SIGINT

eval "$1"
echo >> $TMPFILE

# TODO(jleen): Comment preserved from ancestor.  What does it mean?
# save STDIN to restore for vimdiff
exec 7<&0
eval "\"$VIM_BINARY\" -f '+so $SVCONFIGDIR/share/vimdiff/multidiff.vim' `cat $TMPFILE`"
cleanup
