if [ "$UID" != 0 ]; then
  # This is zshenv but it's useful to have it bash-compatible (so it can be
  # sourced from .xsession, for example).
  if [ -n "$BASH_VERSION" ]; then
    export SVCONFIGDIR=`dirname $(dirname ${BASH_ARGV[0]})`
  else
    export SVCONFIGDIR="${0:h:h}"
  fi

  SVCONFIGPATH=$SVCONFIGDIR/bin
  SVCONFIGFPATH=$SVCONFIGDIR/zsh/functions

  echo $PATH | grep -q $SVCONFIGPATH || PATH=$SVCONFIGPATH:$PATH
  echo $FPATH | grep -q $SVCONFIGFPATH || FPATH=$SVCONFIGFPATH:$FPATH
  echo $PATH | grep -q $HOME/bin || PATH=$HOME/bin:$PATH

  export INPUTRC="$SVCONFIGDIR/inputrc"
  export SCREENRC="$SVCONFIGDIR/screenrc"
fi
