# zshrc sets up aliases, bindings, and anything else that's only needed for
# interactive shells.  This implementation is a stub that sets up basic options
# that everything else depends on, then reads the rest of the configuration from
# the "scripts" directory.

if [[ $UID != 0 && -z $SUDO_USER ]]; then
  setopt hist_ignore_all_dups

  # Pick up the rest of the configuration.
  for rc in $SVCONFIGDIR/zsh/scripts/*.zsh; do
    source $rc
  done
else
  # Minimal configuration for sudo shells.
  if [[ $UID != 0 ]]; then
    PROMPT="<$USER> $HOST [%/]%# "
  else
    PROMPT="$HOST [%/]%# "
  fi
  alias v=vi
  alias vv='vi -R -'
fi
